In [1]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [20]:
df = pd.read_csv('all_files.csv')

In [21]:
df = df.drop(["year_month", "month"], axis=1)
df

,file_name,folder_name,submissions,weight,text,date
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18
...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27

In [22]:
df[df.isna().any(axis=1)]

,file_name,folder_name,submissions,weight,text,date
15,11-13-2- Khalili.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Zoha Khalili Sent: Friday, November 13, ...",NaN
2026,8-8-9 Itzikowitz.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...,NaN
2975,813-19 Sobel.pdf,First Field Review (June - August 2019),1,0.000018,"From: David Sobel Sent: Monday, August 12, 201...",NaN
5175,8--13-19 Hinton.pdf,First Field Review (June - August 2019),1,0.000018,"From: Karen Hinton Sent: Tuesday, August 13, 2...",NaN
6851,Gilly.pdf,Comments Received After Field Review,1,0.000017,Hi!\n\nMy name is Gilly. I'm\nIsraeli-American...,NaN
...,...,...,...,...,...,...
7635,Luo.pdf,Comments Received After Field Review,1,0.000017,Dear California Department of Education Instru...,NaN
7638,Dahl.pdf,Comments Received After Field Review,1,0.000017,"From: Sharon Dahl\nSent: Saturday, August 17, ...",NaN
7642,Hunt.pdf,Comments Received After Field Review,1,0.000017,To: Curriculum Frameworks and Instructional Re...,NaN
7644,Gilad.pdf,Comments Received After Field Review,1,0.000017,"Hait Gilad\n\nThis curriculum is pro-BDS, negl...",NaN
7645,Moore.pdf,Comments Received After Field Review,1,0.000017,Dear California Instructional Quality Commissi...,NaN

In [23]:
manually_dated = pd.read_csv("manually_dated.csv") 

# Set multi-index on keys for both DataFrames
df.set_index(["file_name", "folder_name"], inplace=True)
manually_dated.set_index(["file_name", "folder_name"], inplace=True)

# Use .update() to replace rows in df_main with df_update values
df.update(manually_dated)

# Reset index back to columns
df.reset_index(inplace=True)

df

,file_name,folder_name,submissions,weight,text,date
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18
...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27

In [24]:
df[df.isna().any(axis=1)]

,file_name,folder_name,submissions,weight,text,date
2026,8-8-9 Itzikowitz.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...,NaN
6851,Gilly.pdf,Comments Received After Field Review,1,0.000017,Hi!\n\nMy name is Gilly. I'm\nIsraeli-American...,NaN
6871,MALLIN.pdf,Comments Received After Field Review,1,0.000017,Dear CA Department of Education Ethnic Studies...,NaN
6877,Fabrikant.pdf,Comments Received After Field Review,1,0.000017,I'm very upset about the new Ethics Studies Cu...,NaN
6880,Goldstein2.pdf,Comments Received After Field Review,1,0.000017,Dear Department of Education;\nI am writing to...,NaN
...,...,...,...,...,...,...
7622,Pietruszka.pdf,Comments Received After Field Review,1,0.000017,Dear CA Department of Education Ethnic Studies...,NaN
7635,Luo.pdf,Comments Received After Field Review,1,0.000017,Dear California Department of Education Instru...,NaN
7642,Hunt.pdf,Comments Received After Field Review,1,0.000017,To: Curriculum Frameworks and Instructional Re...,NaN
7644,Gilad.pdf,Comments Received After Field Review,1,0.000017,"Hait Gilad\n\nThis curriculum is pro-BDS, negl...",NaN
7645,Moore.pdf,Comments Received After Field Review,1,0.000017,Dear California Instructional Quality Commissi...,NaN

In [25]:
df = df.dropna()
df

,file_name,folder_name,submissions,weight,text,date
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18
...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27

In [26]:
df["year_month"] = df["date"].str.slice(0, 7)  # "YYYY-MM"
df

/var/folders/p9/vxqrcpp154bd6rgfzqmcdgv40000gn/T/ipykernel_45541/3953771197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["year_month"] = df["date"].str.slice(0, 7)  # "YYYY-MM"

,file_name,folder_name,submissions,weight,text,date,year_month
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13,2020-11
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13,2020-11
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13,2020-11
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19,2020-11
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18,2020-11
...,...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27,2020-10
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30,2020-10
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22,2020-10
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27,2020-10
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27,2020-10

In [28]:
for period, group in df.groupby("year_month"):
    filename = str(period).replace("-", "_") + ".csv"  # "2019_01.csv"
    group.to_csv(filename, index=False)

In [32]:
correct_date = pd.to_datetime('August 12, 2020')
df.loc[1511] = df.loc[1511].copy()  # make sure we're modifying a copy
df.at[1511, 'date_col'] = correct_date.strftime('%Y-%m-%d')  # 2020-08-12
df.at[1511, 'year_month'] = correct_date.strftime('%Y-%m')

/var/folders/p9/vxqrcpp154bd6rgfzqmcdgv40000gn/T/ipykernel_45541/3736598092.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.at[1511, 'date_col'] = correct_date.strftime('%Y-%m-%d')  # 2020-08-12

In [34]:
df[df['file_name'].str.contains('Knoll.pdf')]

,file_name,folder_name,submissions,weight,text,date,year_month,date_col
1511,8-12-29 Knoll.pdf,Comments Received After Field Review,1,0.000017,"From: Sent: Wednesday, August 12, 2020 4:45 PM...",2029-08-12,2020-08,2020-08-12

In [35]:
df.at[1511, 'date'] = '2020-08-12'

In [36]:
df

,file_name,folder_name,submissions,weight,text,date,year_month,date_col
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13,2020-11,NaN
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13,2020-11,NaN
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13,2020-11,NaN
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19,2020-11,NaN
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18,2020-11,NaN
...,...,...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27,2020-10,NaN
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30,2020-10,NaN
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22,2020-10,NaN
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27,2020-10,NaN
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27,2020-10,NaN

In [37]:
df = df.drop('date_col', axis=1)

In [38]:
df

,file_name,folder_name,submissions,weight,text,date,year_month
0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",2020-11-13,2020-11
1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",2020-11-13,2020-11
2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",2020-11-13,2020-11
3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",2020-11-19,2020-11
4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",2020-11-18,2020-11
...,...,...,...,...,...,...,...
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",2020-10-27,2020-10
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",2020-10-30,2020-10
7714,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",2020-10-22,2020-10
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",2020-10-27,2020-10
7716,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",2020-10-27,2020-10

In [39]:
for period, group in df.groupby("year_month"):
    filename = str(period).replace("-", "_") + ".csv"  # "2019_01.csv"
    group.to_csv(filename, index=False)

In [40]:
outlier = pd.read_csv('2010_08.csv')
outlier

,file_name,folder_name,submissions,weight,text,date,year_month
0,Solomon.pdf,Comments Received After Field Review,1,0.000017,"From: David Solomon\nSent: Tuesday, August 20,...",2010-08-20,2010-08

In [42]:
print(outlier['text'])

0    From: David Solomon\nSent: Tuesday, August 20,...
Name: text, dtype: object

In [44]:
pd.set_option('display.max_colwidth', None)

# Now view the full text
print(outlier.loc[0, 'text'])

From: David Solomon
Sent: Tuesday, August 20, 2019 8:34 AM
To: Ethnic Studies <EthnicStudies@cde.ca.gov>
Subject: Anti-Semitic/anti-Israel bias taught in public institutions
To whom it may concern,
It is appalling to witness numerous examples of openly antisemitic/anti-Israel bias that is deemed acceptable in mainstream
society today through the inaction of others or what is allowed in public
school curriculum.
It is sad to see so many organizations that fight for their respective
protected classes they represent have tremendous influence on what is
allowable curriculum yet when it comes to anti-Semitic/anti-Israel bias
there is still serious issues of this kind of propaganda excreting into the
education system that ultimately leads to violence against Jewish
people.
The excrement cited in attached email is an example of a view deemed
acceptable by learning institutions regarding BDS as “a social
organization that defends the rights of another group of people.” A
large number states have already determined BDS to be an anti-Semitic
movement under the guise of a social movement and therefore has
bans in place for involvement with such organizations. To think that the
state of California which claims to be so “progressive “ accepts an
organization that is well known to hold ideologies that incite hatred and
violence towards Jews is indeed very upsetting. Whomever is
responsible for taking action needs to act objectively on all issues
similar to the example cited otherwise s/he is unfit for the position and
should thereby be removed.

Sent from my iPhone