In [1]:
import pandas as pd

In [63]:
df_1 = pd.read_csv("all_files.csv")

In [65]:
df_1[df_1['text'].str.isspace() == True]

,Unnamed: 0,file_name,folder_name,text,submissions,weight
6851,6852,Gilly.pdf,Comments Received After Field Review,,1,0.000017
6881,6882,9-30-19 Fisher et al.pdf,Comments Received After Field Review,,1,0.000017
6883,6884,Greenbaum.pdf,Comments Received After Field Review,,1,0.000017
6888,6889,H.pdf,Comments Received After Field Review,,1,0.000017
6910,6911,Lavic.pdf,Comments Received After Field Review,,1,0.000017
6932,6933,Shugarman.pdf,Comments Received After Field Review,,1,0.000017
6967,6968,Rones.pdf,Comments Received After Field Review,,1,0.000017
6991,6992,Draper.pdf,Comments Received After Field Review,,1,0.000017
6995,6996,Kean Gold.pdf,Comments Received After Field Review,,1,0.000017
7000,7001,Brunshteyn.pdf,Comments Received After Field Review,,1,0.000017
7020,7021,10-21-19 Coodley.pdf,Comments Received After Field Review,,1,0.000017
7026,7027,Guelfand.pdf,Comments Received After Field Review,,1,0.000017
7027,7028,Lebowitz.pdf,Comments Received After Field Review,,1,0.000017
7041,7042,Caballero.pdf,Comments Received After Field Review,,1,0.000017
7046,7047,Young.pdf,Comments Received After Field Review,,1,0.000017
7054,7055,Fuks.pdf,Comments Received After Field Review,,1,0.000017
7077,7078,Alkana.pdf,Comments Received After Field Review,,1,0.000017
7094,7095,Lieberman.pdf,Comments Received After Field Review,,1,0.000017
7096,7097,Northrup.pdf,Comments Received After Field Review,,1,0.000017
7098,7099,Baruch 2.pdf,Comments Received After Field Review,,1,0.000017
7105,7106,9-17-19 Gatto.pdf,Comments Received After Field Review,,1,0.000017
7110,7111,Sacks.pdf,Comments Received After Field Review,,1,0.000017
7113,7114,8-30-19 Sleeter.pdf,Comments Received After Field Review,,1,0.000017
7116,7117,9-6-19 Kaiser.pdf,Comments Received After Field Review,,1,0.000017
7117,7118,7-17-20 Portantino et al.pdf,Comments Received After Field Review,,1,0.000017
7128,7129,Cirocco.pdf,Comments Received After Field Review,,1,0.000017
7160,7161,8-22-19 Kehlmann.pdf,Comments Received After Field Review,,1,0.000017
7165,7166,Yee.pdf,Comments Received After Field Review,,1,0.000017
7175,7176,Gilboa.pdf,Comments Received After Field Review,,1,0.000017
7200,7201,Abigail.pdf,Comments Received After Field Review,,1,0.000017
7217,7218,Bradley.pdf,Comments Received After Field Review,,1,0.000017
7298,7299,9-3-19 Wynn.pdf,Comments Received After Field Review,,1,0.000017
7300,7301,1-16-20 Save CA Ethnic Studies.pdf,Comments Received After Field Review,,1,0.000017
7325,7326,Eshoo.pdf,Comments Received After Field Review,,1,0.000017
7342,7343,10-21-19 Huckabay.pdf,Comments Received After Field Review,,1,0.000017
7358,7359,Robertson.pdf,Comments Received After Field Review,,1,0.000017
7363,7364,Wiener Gloria.pdf,Comments Received After Field Review,,1,0.000017
7426,7427,Gallagher.pdf,Comments Received After Field Review,,1,0.000017
7452,7453,9-5-19 Cerruti.pdf,Comments Received After Field Review,,1,0.000017
7485,7486,Ariel.pdf,Comments Received After Field Review,,1,0.000017
7506,7507,9-5-19 Ma.pdf,Comments Received After Field Review,,1,0.000017
7525,7526,B.pdf,Comments Received After Field Review,,1,0.000017
7526,7527,1-9-20 Adelberg.pdf,Comments Received After Field Review,,1,0.000017
7531,7532,Rutman.pdf,Comments Received After Field Review,,1,0.000017
7544,7545,Musayev.pdf,Comments Received After Field Review,,1,0.000017
7566,7567,Baruch.pdf,Comments Received After Field Review,,1,0.000017
7570,7571,Velazquez.pdf,Comments Received After Field Review,,1,0.000017
7578,7579,Plack.pdf,Comments Received After Field Review,,1,0.000017
7587,7588,Lahav.pdf,Comments Received After Field Review,,1,0.000017
7593,7594,Moss.pdf,Comments Received After Field Review,,1,0.000017
7605,7606,8-26-19 Breslauer.pdf,Comments Received After Field Review,,1,0.000017
7620,7621,Roder.pdf,Comments Received After Field Review,,1,0.000017
7628,7629,Bertet.pdf,Comments Received After Field Review,,1,0.000017

In [66]:
df["file_name"] = df["file_name"].str.replace(".txt", ".pdf", regex=False)

In [67]:
df

,file_name,text
0,Baruch 2.pdf,"Helio,\n\nlam a community member deeply concer..."
1,Northrup.pdf,AGOURA HILLS\n\nLinda Nortartip/\n\n“Gateway t...
2,9-17-19 Gatto.pdf,Board of Directors\nTHE HISTORIC ITALIAN HALL\...
3,Sacks.pdf,jk urnce te Ch biFoRin Doe\n\ntm Reuse twe Eth...
4,8-30-19 Sleeter.pdf,ed. . oe\nCALIFORNIA STATE UNIVERSITY\n(GP) Ni...
5,9-6-19 Kaiser.pdf,"P. O. Box 7655\nMenlo Park, CA\n9/3/19\n\nMr. ..."
6,7-17-20 Portantino et al.pdf,"July 17, 2020\n\nThe Honorable Tony Thurmond\n..."
7,Cirocco.pdf,"August 9, 2019\n\nMs. Soomin Chao\n\nChair, In..."
8,Fuks.pdf,My nome is Maor Pus. | SEW YORK NY\n\nIsracli-...
9,Alkana.pdf,Eugene S. Alkana\nA PROFESSIONAL LAW CORPORATI...
10,Lieberman.pdf,"August 9, 2019\n\nMs. Soomin Chao\n\nChair, In..."
11,Bradley.pdf,"Ms. Soomin Chao\n\nChair, lnstructional Qualit..."
12,8-22-19 Kehlmann.pdf,"August 16, 2019\n\nThe Honorable Tony Thurmond..."
13,Yee.pdf,Betry T. YEE\n\nCalifornia State Controller\nA...
14,Gilboa.pdf,Public Input Template—2020 Ethnic Studies Mode...
15,Abigail.pdf,"Hi there!\nMy name is Abigail. | OPER aes, $6 ..."
16,Lavic.pdf,"Hil\n\n: ty\nMy wade is Liaw, Sow feurish ‘wr ..."
17,Shugarman.pdf,"August 9, 2019\n\nMs. Soomin Chao\n\nChair, In..."
18,Gilly.pdf,Hi!\n\nMy name is Gilly. I'm\nIsraeli-American...
19,Greenbaum.pdf,2020 Ethnic Studies. Model Curriculum\nAdvisor...
20,9-30-19 Fisher et al.pdf,"September 11, 2019\n\nCalifornia Department of..."
21,H.pdf,"August 9, 2019\n\nMs. Soomin Chao\n\nChair, In..."
22,10-21-19 Coodley.pdf,"80 Harvard\nNapa, CA\nAugust 30, 2019\n\nTo: C..."
23,Guelfand.pdf,"Aug. 12, 2019\n\nTo: 2020 Ethnic Studies Model..."
24,Lebowitz.pdf,"Maxine'and Stephen Lebowitz\n2217 W. 25"" Stree..."
25,Caballero.pdf,"California State Senate\n\nSTATE CAPITOL, COMM..."
26,Young.pdf,"April 14, 2019\n\nCalifornia Department of Edu..."
27,Rones.pdf,eo\n\nMs. Shulamith Rones\n572 Avenida Sevilla...
28,Draper.pdf,To whom it Way concern. The&tanice Studres cl....
29,Kean Gold.pdf,4eyD peo: J22YO BANNDAXg JalyD\nplod ajausiw u...
30,Brunshteyn.pdf,"To whom it.may concern,\n\nThe Department of E..."
31,1-9-20 Adelberg.pdf,"MICHAEL G, ADELBERG\n\n1205 Lantérn CT State S..."
32,B.pdf,"Ms. Soomin Chao\n\nChair, Instructional Qualit..."
33,Rutman.pdf,"August 12, 2019\n\nMs. Soomin Chao\n\nChair, I..."
34,9-5-19 Cerruti.pdf,California Italian-American Task Force\n\nP.O....
35,Moss.pdf,LAW OFFICES OF RICHARD F.1'-1OSS\n6345 Balboa ...
36,8-26-19 Breslauer.pdf,"genJJ breskuer\n\nAugust 19, 2019\nMs. Soomin ..."
37,Roder.pdf,"FREDRICKL. RODER,Ph.D.\n2112 Century Park Lane..."
38,Bertet.pdf,"Julian Bertet\n4121 Vantage Ave.\nStudio City,..."
39,Musayev.pdf,"Iliya Musayev\n3339 Isherwood Way,\nFremont CA..."
40,Baruch.pdf,"Hello,\nI'm writing to you as a CA resident an..."
41,Plack.pdf,Linda Festa Plack\n426 Urbano Drive\nSan Franc...
42,Velazquez.pdf,Robert Velazquez\n2670 American River Drive\nS...
43,Lahav.pdf,Hi!\nMy name is Adir. I’m jewish-American\nand...
44,9-3-19 Wynn.pdf,SAA ~GLaz4\n\nState Superintendent\n\nof Publi...
45,1-16-20 Save CA Ethnic Studies.pdf,Save CA Ethnic Studies Coalition\n\nPublic Com...
46,Eshoo.pdf,Congress of the United States\nHouse 6 Teepwre...
47,10-21-19 Huckabay.pdf,"August 23, 2019\n\nHonorable Mr. Tony Thurmond..."
48,Gallagher.pdf,COMMITTEES STATE CAPITOL\nVICE CHAIR: ELECTION...
49,Robertson.pdf,"eegust JG, ZOU\n\nMs. Soomin Chao\n\nChair, In..."
50,Wiener Gloria.pdf,"Senator Scott Wiener, Chair\n\n: Assemblymembe..."

In [68]:
df_1 = df_1.drop(columns=["text"]).merge(df, on="file_name", how="left").fillna(df_1)

In [69]:
df_1[df_1['text'].str.isspace() == True]

,Unnamed: 0,file_name,folder_name,submissions,weight,text
7485,7486,Ariel.pdf,Comments Received After Field Review,1,0.000017,
7506,7507,9-5-19 Ma.pdf,Comments Received After Field Review,1,0.000017,

In [71]:
folder_path = "../../../clean_1"

data = []
for file_name in os.listdir(folder_path):
    if file_name.endswith(".txt"):  # Process only .txt files
        file_path = os.path.join(folder_path, file_name)
        with open(file_path, "r", encoding="utf-8") as f:
            data.append({"file_name": file_name, "text": f.read()})

df_2 = pd.DataFrame(data)
df_2

       file_name                                               text
0  9-5-19 Ma.txt  ,,{'sur.\n'"\n\nt;11U.1\A\n\n.M·~\n\n~\nm!i'\n...
1      Ariel.txt  Hello!\nMy name is Ariel and I’m a High School...

In [72]:
df_2["file_name"] = df_2["file_name"].str.replace(".txt", ".pdf", regex=False)

In [73]:
df_2

       file_name                                               text
0  9-5-19 Ma.pdf  ,,{'sur.\n'"\n\nt;11U.1\A\n\n.M·~\n\n~\nm!i'\n...
1      Ariel.pdf  Hello!\nMy name is Ariel and I’m a High School...

In [74]:
df_1["text"] = df_1["file_name"].map(df_2.set_index("file_name")["text"]).fillna(df_1["text"])
df_1

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [75]:
df_1[df_1['text'].str.isspace() == True]

Empty DataFrame
Columns: [Unnamed: 0, file_name, folder_name, submissions, weight, text]
Index: []

In [76]:
df_1.to_csv("all_files.csv", index=False, encoding="utf-8")

In [77]:
all = pd.read_csv("all_files.csv")
all

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."