In [1]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('all_files.csv')

In [3]:
df

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [10]:
armenia = df[df['text'].str.contains('armenia', case=False)]
armenia

,Unnamed: 0,file_name,folder_name,submissions,weight,text
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
19,19,11-13-20 Armen et al.pdf,"Comments Received After September 30, 2020",1,0.000008,"Dear IQC,\n\nWe are scholars with a specific s..."
26,26,11-13-20 Post .pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Lauren Post Sent: Friday, November 13, 2..."
52,52,11-18-20 Penhaskashi.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: JADEN PENHASKASHI Sent: Wednesday, Novem..."
74,74,11-13-20 Paperman.pdf,"Comments Received After September 30, 2020",1,0.000008,Debbie Paperman Board Member Democrats for Isr...
...,...,...,...,...,...,...
7574,7575,7-30-20 Okoomian.pdf,Comments Received After Field Review,1,0.000017,29 July 2020\nRegarding: State of California E...
7584,7585,9-13-19 Takhsh.pdf,Comments Received After Field Review,1,0.000017,"From: Ramond Takhsh\nSent: Friday, September 1..."
7600,7601,7-13-20 Armenian American Studies Collective.pdf,Comments Received After Field Review,1,0.000017,"July 13, 2020\n\nIn Support of Ethnic Studies ..."
7654,7655,10-7-20 Deurdulian.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Corinne Deurdulian\nSent: Wednesday, Oct..."
7701,7702,10-23-20 Karapetian.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Shushan Karapetian\nSent: Friday, Octobe..."

In [18]:
print(armenia['text'].iloc[9])

-----Original Message----From: [Emails redacted] Sent: Thursday, November 19, 2020 12:08 AM To: Ethnic Studies Subject: [EXTERNAL] CA Ethnic Studies must include West Asian Studies

Dear Instructional Quality Commission of the California Board of Education,

In recent years the Iranian-American community has faced continuous challenges, from the Muslim ban that prevents our families from traveling to the U.S., to the persistent fear of war, and a rising atmosphere of discrimination. But we are certainly not alone. In these times, studies of Orientalism, anti-Muslim racism, critical refugee studies, and our diasporan experience of colonization(s), help youth make sense of their realities. While civic engagement is crucial to our ability to make a difference, real change must also be implemented across our society. That is why I was excited for the inclusion of ethnic studies curriculum in K-12 school. But now I am appalled at the recent draft of the model curriculum - a draft that is completely devoid of the spirit and pedagogy of ethnic studies.

The West Asian community comprises a large portion of California's cultural tapestry. Los Angeles alone is home to the largest Iranian diaspora in the world. Yet the model curriculum only presents a narrow lens on our community, only choosing to focus on the Iranian Revolution and not the additional historical and sociocultural experiences that comprise our community. Our community is not the only West Asian community that is erased in this draft. I am also concerned that the recent draft removed Arab American and Pacific Islander studies, further erasing critical communities that make up California's rich diversity.

Education is a key location for marginalized people to be represented. As such, I call on the CDE to:

1. Include "West Asian Studies" to the Ethnic Studies Model Curriculum (ESMC) to ensure that Arab, Iranian, Armenian, Palestinian, Kurdish, Afghan, Turkish, and Assyrian Americans, among others, are included.

2. Ensure that the curriculum about a community of people is made in consultation with stakeholders and ethnic studies practitioners from these communities. For example, curriculum written about the Iranian diaspora should be done in consultation, or even written by, ethnic studies practitioners from the Iranian diaspora community.

3. Restore the original draft of the ESMC and reconvene the original committee of writers and experts to revise a draft as Ethnic Studies scholars and teachers are the experts on Ethnic Studies curriculum and pedagogy.



For our own community, it is important that young Iranian Americans see themselves represented in their education. Not only as part of the diverse milieu of the American experience, but also for the contributions of Iranian history and culture to world history. Iranian Americans should be proud of their culture and history at home, as well as the culture and history of their heritage.

Our students are growing up in a world which normalizes these diverse realities. U.S. Ethnic Studies allows for and offers the tools for marginalized students to unpack and unlearn structures of power and have access to empowered education and pedagogy. Learning about the various histories of all Americans will provide our students with a complete picture of the United States and society we all share.

Sincerely, Mr. JASON SAVILLE