In [2]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv('all_files.csv')
df

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [4]:
import pandas as pd

# Example DataFrame

# Check which rows are empty or just spaces
empty_mask = df['text'].str.strip().eq('') | df['text'].isna()

df[empty_mask]

Empty DataFrame
Columns: [Unnamed: 0, file_name, folder_name, submissions, weight, text]
Index: []

In [5]:
import string
def is_illegible(s):
    if pd.isna(s) or s.strip() == '':
        return False  # treat empty as separate case
    return any(c not in string.printable for c in s)


illegible_rows = df[df['text'].apply(is_illegible)]

illegible_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
5,5,11-17-20 Yardeni.pdf,"Comments Received After September 30, 2020",1,0.000008,----------------------------------------------...
13,13,11-13-20 Epstein et al.pdf,"Comments Received After September 30, 2020",1,0.000008,Dear Members of the Instructional Quality Comm...
15,15,11-13-2- Khalili.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Zoha Khalili Sent: Friday, November 13, ..."
16,16,11-11-20 DePass.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Linval DePass Sent: Wednesday, November ..."
17,17,11-13-20 Homsi.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Pauline Homsi Sent: Friday, November 13,..."
...,...,...,...,...,...,...
7709,7710,10-2-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 2, 20..."
7710,7711,10-2-20 Boyd.pdf,"Comments Received After September 30, 2020",1,0.000008,"October 2, 2020\nPresident\nE. Toby Boyd\n\nTO..."
7711,7712,10-14-20 George.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: IQC\nSent: Wednesday, October 14, 2020 1..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."

In [6]:
import re
import pandas as pd

def legibility_metrics(s):
    if pd.isna(s) or not isinstance(s, str) or s.strip() == '':
        return {"alpha_ratio": 0, "word_ratio": 0, "weird_char_ratio": 0}
    
    s_clean = s.replace('\n', ' ').replace('\r', ' ')
    total_chars = len(s_clean)
    alpha_chars = sum(c.isalpha() for c in s_clean)
    alpha_ratio = alpha_chars / total_chars if total_chars > 0 else 0

    words = re.findall(r'[A-Za-z]{2,}', s_clean)
    word_ratio = len(words) / (total_chars / 5) if total_chars > 0 else 0

    weird_char_ratio = sum(not (c.isalnum() or c.isspace()) for c in s_clean) / total_chars

    return {
        "alpha_ratio": alpha_ratio,
        "word_ratio": word_ratio,
        "weird_char_ratio": weird_char_ratio
    }

# Apply and add to df
metrics = df['text'].apply(legibility_metrics).apply(pd.Series)
df_metrics = pd.concat([df, metrics], axis=1)

In [7]:
df_metrics[['alpha_ratio', 'word_ratio', 'weird_char_ratio']].describe()

       alpha_ratio   word_ratio  weird_char_ratio
count  7717.000000  7717.000000       7717.000000
mean      0.790383     0.738118          0.030825
std       0.025821     0.044306          0.011637
min       0.333333     0.043838          0.000000
25%       0.783047     0.709681          0.024486
50%       0.795695     0.736152          0.028606
75%       0.805656     0.764563          0.033719
max       0.871165     0.948827          0.253937

In [8]:
alpha_low = df_metrics['alpha_ratio'].mean() - 3 * df_metrics['alpha_ratio'].std()   # unusually low alphabetic %
word_low = df_metrics['word_ratio'].mean() - 3 * df_metrics['word_ratio'].std()     # unusually low English word %
weird_high = df_metrics['weird_char_ratio'].mean() + 3 * df_metrics['weird_char_ratio'].std()  # unusually high symbol %

illegible_rows = df[
    (df_metrics['alpha_ratio'] < alpha_low) |
    (df_metrics['word_ratio'] < word_low) |
    (df_metrics['weird_char_ratio'] > weird_high)
]

illegible_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
5,5,11-17-20 Yardeni.pdf,"Comments Received After September 30, 2020",1,0.000008,----------------------------------------------...
13,13,11-13-20 Epstein et al.pdf,"Comments Received After September 30, 2020",1,0.000008,Dear Members of the Instructional Quality Comm...
86,86,11-11-20 Guttenberg.pdf,"Comments Received After September 30, 2020",1,0.000008,-----Original Message----From: martaguttenberg...
133,133,11-13-20 Silton.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: On Behalf Of Lynn Silton Sent: Friday, N..."
139,139,11-10-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Tuesday, November 10, ..."
...,...,...,...,...,...,...
7673,7674,10-27-20 Cohen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ken Cohen\nSent: Monday, October 26, 202..."
7684,7685,11-2-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, November 2, 2..."
7691,7692,10-14-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 13, ..."
7692,7693,10-26-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."

In [9]:
# Recalculate new (looser) thresholds
alpha_low_2 = df_metrics['alpha_ratio'].mean() - 2 * df_metrics['alpha_ratio'].std()
word_low_2 = df_metrics['word_ratio'].mean() - 2 * df_metrics['word_ratio'].std()
weird_high_2 = df_metrics['weird_char_ratio'].mean() + 2 * df_metrics['weird_char_ratio'].std()

# Run again to find more rows that look illegible under looser rules
illegible_rows_looser = df[
    (df_metrics['alpha_ratio'] < alpha_low_2) |
    (df_metrics['word_ratio'] < word_low_2) |
    (df_metrics['weird_char_ratio'] > weird_high_2)
]

# Keep only new ones not in the first batch
new_illegible_rows = illegible_rows_looser.loc[
    ~illegible_rows_looser.index.isin(illegible_rows.index)
]

new_illegible_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
105,105,11-12-20 Kaufman.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Jon Kaufman Sent: Thursday, November 12,..."
175,175,11-18-20 Hsiao.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Rod Hsiao Sent: Wednesday, November 18, ..."
177,177,11-13-20 Baha.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Omar Baha Sent: Friday, November 13, 202..."
200,200,11-13-20 Webber Attachment 1.pdf,"Comments Received After September 30, 2020",1,0.000008,Arabic 367: American Identity in the World Ara...
250,250,11-13-20 Chang Attachment 2.pdf,"Comments Received After September 30, 2020",1,0.000008,1 This lesson was submitted by a member(s) of ...
...,...,...,...,...,...,...
7699,7700,10-13-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 13, ..."
7700,7701,10-1-20 Klein.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Steve Klein\nSent: Thursday, October 1, ..."
7705,7706,10-19-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 19, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

# Antisemitism Sampling

In [133]:
antisemitism_variants = [
    'antisemitism',
    'anti-semitism',
    'anti semitism',
    'antisemitic',
    'anti-semitic',
    'anti semitic',
    'antisemite',
    'anti-semite',
    'anti semite',
    'antisemitisim',
    'antisemitsm',
    'antisemitizm',
    'anti-semitizm',
    'anti semitizm',
    'ant1semitism',
    'anti$emitism',
    'anti-semit1sm',
    'anti semit1sm'
]

pattern = '|'.join(antisemitism_variants)

matched_rows = df[df['text'].str.contains(pattern, case=False, na=False)]

matched_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
5,5,11-17-20 Yardeni.pdf,"Comments Received After September 30, 2020",1,0.000008,----------------------------------------------...
8,8,11-16-20 Landau.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: nonielandau Sent: Friday, November 13, 2..."
9,9,11-18-20 Donsky.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Joanne Donsky Sent: Wednesday, November ..."
...,...,...,...,...,...,...
7707,7708,10-12-20 Haufrect.pdf,"Comments Received After September 30, 2020",1,0.000008,Public Input Template–2020 Ethnic Studies Mode...
7708,7709,10-30-20 Meyers and Shmueli 2.pdf,"Comments Received After September 30, 2020",1,0.000008,Educators for Excellence in Ethnic Studies\n\n...
7709,7710,10-2-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 2, 20..."
7711,7712,10-14-20 George.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: IQC\nSent: Wednesday, October 14, 2020 1..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."

In [134]:
matched_rows['submissions'].sum()

20519

In [ ]:
antisemitism_samples = df.sample(n=40, replace=True, random_state=42)
antisemitism_samples

# Recurring Authors

In [22]:
df = pd.read_csv('all_files.csv')
df

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [23]:
authors = df['file_name'].str.extract(r'\d{1,2}-\d{1,2}-\d{2}\s+(.*?)\.pdf')

author_counts = authors[0].value_counts().reset_index()
author_counts.columns = ['author', 'count']

In [24]:
author_counts[author_counts['count'] > 1]

       author  count
0      Parker     46
1       Cohen     23
2       Smith     17
3    Schwartz     15
4       Levin     14
..        ...    ...
967    Herman      2
968    Bender      2
969     LeMay      2
970     Ellis      2
971    Milder      2

[972 rows x 2 columns]

In [58]:
author_counts.head(70)

      author  count
0     Parker     46
1      Cohen     23
2      Smith     17
3   Schwartz     15
4      Levin     14
..       ...    ...
65      Ross      6
66     Clark      6
67   Freeman      6
68   Goldman      6
69    Marcus      6

[70 rows x 2 columns]

In [26]:
author_parker = df[df['file_name'].str.contains('Parker', case=False)]

In [27]:
author_parker[author_parker['text'].str.contains('Ruth', case=False)]
ruth_parker = author_parker.drop(['Unnamed: 0', 'submissions', 'weight'], axis=1)
ruth_parker

,file_name,folder_name,text
46,11-13-20 Parker Ella.pdf,"Comments Received After September 30, 2020","From: Ella Parker Sent: Friday, November 13, 2..."
54,11-12-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ella Parker Sent: Thursday, November 12,..."
61,11-29-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ruth Parker Sent: Sunday, November 29, 2..."
75,11-13-20 Parker.pdf,"Comments Received After September 30, 2020","From: Maria Parker Sent: Friday, November 13, ..."
83,11-19-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ruth Parker Sent: Thursday, November 19,..."
...,...,...,...
7706,10-12-20 Parker 2.pdf,"Comments Received After September 30, 2020","From: Ruth Parker\nSent: Monday, October 12, 2..."
7709,10-2-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ruth Parker\nSent: Friday, October 2, 20..."
7712,10-27-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,10-30-20 Parker.pdf,"Comments Received After September 30, 2020","From: Ruth Parker\nSent: Friday, October 30, 2..."
7715,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020","From: Ruth Parker\nSent: Tuesday, October 27, ..."

In [28]:
ruth_parker.to_csv('ruth_parker.csv', index=False)

In [29]:
df[df['text'].str.contains('Ruth Parker', case=False)]

,Unnamed: 0,file_name,folder_name,submissions,weight,text
61,61,11-29-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Sunday, November 29, 2..."
83,83,11-19-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Thursday, November 19,..."
90,90,12-3-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Thursday, December 3, ..."
110,110,11-17-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Tuesday, November 17, ..."
139,139,11-10-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker Sent: Tuesday, November 10, ..."
...,...,...,...,...,...,...
7709,7710,10-2-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 2, 20..."
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [30]:
print(df.iloc[7716]['text'])

From: Sue Fishkoff
Sent: Monday, October 26, 2020 6:28 PM
To: Ruth Parker
Cc: [list of other recipients redacted]; Ethnic Studies
Subject: [EXTERNAL] Re: Fw: A forward from J. Barry's friend, Marilyn; how can any self-respecting
person trust the NYT after knowing this?
Ruth,
This is Sue Fishkoff here, editor of J. The Jewish News of Northern California. I'm glad I'm on your email
list, because I can allay your fears.
What you have sent us is a piece of satire created in 2006, to protest the Israeli operation in Lebanon.
The real May 10, 1943 front page of the New York Times is here (you have to scroll down past the fake
front page, the explanation, and then you get to the real front page, which you can verify on the New
York Times website itself):
https://www.snopes.com/fact-check/warsaw-ghetto-uprising/
It is awful to see this true "fake news." Whatever you think of the New York Times, it would never have
published such Nazi propaganda.
Regards,
Sue
On Mon, Oct 26, 2020 at 5:41 PM Ruth Parker wrote:
I have seen this picture so many times and never until now knew that it appeared on the front page of the
New York Times with headlines blaming the Jews for their own destruction.
----- Forwarded Message ----From: J. Barry Gurdin
To: Ruth Parker; [list of other recipients redacted]
Sent: Monday, October 26, 2020, 04:28:06 PM PDT
Subject: A forward from J. Barry's friend, Marilyn; how can any self-respecting person trust the NYT after
knowing this?

--

Sue Fishkoff
Editor

In [62]:
# 1. Extract authors from filenames and get top 100
author_counts = (
    df['file_name']
    .str.extract(r'\d{1,2}-\d{1,2}-\d{2}\s+(.*?)\.pdf')[0]
    .value_counts()
)

top_authors = author_counts.head(100).index

# 2. Extract all "From:" names for the top 100 authors
all_names = []

for author in top_authors:
    subset = df[df['file_name'].str.contains(author, case=False)].copy()
    names = subset['text'].str.extract(r'From:\s*(.*?)\s+Sent:', expand=False)
    all_names.append(names)

# 3. Combine and get top 10 names
top_15 = (
    pd.concat(all_names)
    .value_counts()
    .head(15)
)

top_15

text
Ruth Parker               78
Sondra Goldstein           9
Victoria Wong              7
JEFFREY CARMEL             6
Nora Rousso                6
[email redacted]           6
                           6
Joanne Donsky              6
Joe Nalven                 5
Kim Green                  5
Cynthia Chang              5
Lee, Roselinn ( Linn )     4
Kathy Jordan               4
Linda Brownstein           4
HELEN WEINSTEIN            4
Name: count, dtype: int64

# Mentions of BDS

In [135]:
bds_variants = [
    'bds',
    'B.D.S.',
    'Boycott, Divestment, and Sanctions',
    'Boycott, Divestment, and Sanction',
    'Boycott & Divestment',
    'Boycott and Divestment'
]

pattern = '|'.join(bds_variants)

matched_rows = df[df['text'].str.contains(pattern, case=False, na=False)]
matched_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
38,38,11-23-20 Goldfinger.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Robin Goldfinger Sent: Saturday, Novembe..."
52,52,11-18-20 Penhaskashi.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: JADEN PENHASKASHI Sent: Wednesday, Novem..."
58,58,11-12-20 Kay.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sheila Kay Sent: Thursday, November 12, ..."
70,70,"11-08-20 Smith, Gregory.pdf","Comments Received After September 30, 2020",1,0.000008,"From: Greg Smith Sent: Sunday, November 8, 202..."
74,74,11-13-20 Paperman.pdf,"Comments Received After September 30, 2020",1,0.000008,Debbie Paperman Board Member Democrats for Isr...
...,...,...,...,...,...,...
7667,7668,11-4-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Wednesday, November 4..."
7679,7680,10-5-20 Chiu.pdf,"Comments Received After September 30, 2020",1,0.000008,"September 30, 2020\nInstructional Quality Comm..."
7691,7692,10-14-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 13, ..."
7707,7708,10-12-20 Haufrect.pdf,"Comments Received After September 30, 2020",1,0.000008,Public Input Template–2020 Ethnic Studies Mode...
7711,7712,10-14-20 George.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: IQC\nSent: Wednesday, October 14, 2020 1..."

In [136]:
matched_rows['submissions'].sum()

7402

# Mentions of Nakba

In [137]:
nakba_variants = [
    'nakba',
    'Nakbah',
    '1948',
    'War of Independence',
    'Arab–Israeli War'
]

pattern = '|'.join(nakba_variants)

matched_rows = df[df['text'].str.contains(pattern, case=False, na=False)]
matched_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
20,20,11-18-20 Smith.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Warren Smith Sent: Wednesday, November 1..."
41,41,11-12-20 Galal.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: KGalal Sent: Thursday, November 12, 2020..."
79,79,11-12-20 Lepawsky.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Jed Linden Sent: Thursday, November 12, ..."
108,108,11-13-20 Lavie.pdf,"Comments Received After September 30, 2020",1,0.000008,"Smadar Lavie, PhD Professor Emerita of Anthrop..."
114,114,11-13-20 Shoman Attachment.pdf,"Comments Received After September 30, 2020",1,0.000008,Arab Americans\n\nSample Lesson: Understanding...
...,...,...,...,...,...,...
7622,7623,Pietruszka.pdf,Comments Received After Field Review,1,0.000017,Dear CA Department of Education Ethnic Studies...
7628,7629,Bertet.pdf,Comments Received After Field Review,1,0.000017,"Julian Bertet\n4121 Vantage Ave.\nStudio City,..."
7651,7652,10-5-20 Smith Attachment.pdf,"Comments Received After September 30, 2020",1,0.000008,"COMMUNISM\nITS IDEOLOGY, ITS HISTORY,\nAND ITS..."
7707,7708,10-12-20 Haufrect.pdf,"Comments Received After September 30, 2020",1,0.000008,Public Input Template–2020 Ethnic Studies Mode...
7711,7712,10-14-20 George.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: IQC\nSent: Wednesday, October 14, 2020 1..."

In [138]:
matched_rows['submissions'].sum()

2082

In [70]:
matched_rows[matched_rows['text'].str.contains('1948', case=False, na=False)]

,Unnamed: 0,file_name,folder_name,submissions,weight,text
41,41,11-12-20 Galal.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: KGalal Sent: Thursday, November 12, 2020..."
108,108,11-13-20 Lavie.pdf,"Comments Received After September 30, 2020",1,0.000008,"Smadar Lavie, PhD Professor Emerita of Anthrop..."
114,114,11-13-20 Shoman Attachment.pdf,"Comments Received After September 30, 2020",1,0.000008,Arab Americans\n\nSample Lesson: Understanding...
117,117,11-13-20 Gutierrez.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Andrew Paul Gutierrez Sent: Friday, Nove..."
211,211,11-16-20 Dibas.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Nada Dibas Sent: Friday, November 13, 20..."
...,...,...,...,...,...,...
7619,7620,7-29-20 Institute for Curriculum Services.pdf,Comments Received After Field Review,1,0.000017,Jewish American Studies Course Outline:\nThe J...
7622,7623,Pietruszka.pdf,Comments Received After Field Review,1,0.000017,Dear CA Department of Education Ethnic Studies...
7651,7652,10-5-20 Smith Attachment.pdf,"Comments Received After September 30, 2020",1,0.000008,"COMMUNISM\nITS IDEOLOGY, ITS HISTORY,\nAND ITS..."
7707,7708,10-12-20 Haufrect.pdf,"Comments Received After September 30, 2020",1,0.000008,Public Input Template–2020 Ethnic Studies Mode...
7711,7712,10-14-20 George.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: IQC\nSent: Wednesday, October 14, 2020 1..."

In [139]:
nakba_variants = [
    'nakba',
    'Nakbah',
    'War of Independence',
    'Arab–Israeli War'
]

pattern = '|'.join(nakba_variants)

matched_rows = df[df['text'].str.contains(pattern, case=False, na=False)]
matched_rows

,Unnamed: 0,file_name,folder_name,submissions,weight,text
20,20,11-18-20 Smith.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Warren Smith Sent: Wednesday, November 1..."
79,79,11-12-20 Lepawsky.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Jed Linden Sent: Thursday, November 12, ..."
108,108,11-13-20 Lavie.pdf,"Comments Received After September 30, 2020",1,0.000008,"Smadar Lavie, PhD Professor Emerita of Anthrop..."
114,114,11-13-20 Shoman Attachment.pdf,"Comments Received After September 30, 2020",1,0.000008,Arab Americans\n\nSample Lesson: Understanding...
131,131,11-12-20 Koatz.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: B Koatz Sent: Thursday, November 12, 202..."
...,...,...,...,...,...,...
7466,7467,7-27-20 Shapiro.pdf,Comments Received After Field Review,1,0.000017,"From: Larry Shapiro\nSent: Sunday, July 26, 20..."
7549,7550,7-13-20 Abdulhadi et al.pdf,Comments Received After Field Review,1,0.000017,CALIFORNIA SCHOLARS FOR ACADEMIC FREEDOM\nhttp...
7597,7598,1-13-20 Fouda.pdf,Comments Received After Field Review,1,0.000017,"From: MARGARET FOUDA\nSent: Sunday, January 12..."
7605,7606,8-26-19 Breslauer.pdf,Comments Received After Field Review,1,0.000017,"genJJ breskuer\n\nAugust 19, 2019\nMs. Soomin ..."
7628,7629,Bertet.pdf,Comments Received After Field Review,1,0.000017,"Julian Bertet\n4121 Vantage Ave.\nStudio City,..."

In [140]:
matched_rows['submissions'].sum()

334

# Duplicate Comments

In [81]:
duplicates = df[df['text'].str.contains('Education received', case=False)]

In [86]:
duplicates

,Unnamed: 0,file_name,folder_name,submissions,weight,text
30,30,11-12-20 Group Letter Critical Race Theory.pdf,"Comments Received After September 30, 2020",5,0.000040,The California Department of Education receive...
42,42,11-12-20 Group Letter Protect Butler.pdf,"Comments Received After September 30, 2020",3100,0.024743,The California Department of Education receive...
160,160,11-11-20 Group Letter Arab Americans 2.pdf,"Comments Received After September 30, 2020",4600,0.036716,The California Department of Education receive...
224,224,11-11-20 Group Letter Remove Political Agenda.pdf,"Comments Received After September 30, 2020",273,0.002179,The California Department of Education receive...
262,262,11-11-20 Group Letter Guiding Principles.pdf,"Comments Received After September 30, 2020",271,0.002163,The California Department of Education receive...
...,...,...,...,...,...,...
7056,7057,7-8-20 Group Letter Arab American Studies.pdf,Comments Received After Field Review,10000,0.173633,The California Department of Education receive...
7180,7181,7-24-20 Group Letter Protest Draft.pdf,Comments Received After Field Review,200,0.003473,The California Department of Education receive...
7455,7456,1-29-20 Group Email Arab American Studies.pdf,Comments Received After Field Review,900,0.015627,The California Department of Education receive...
7477,7478,7-8-20 Group Letter anti-BDS.pdf,Comments Received After Field Review,8,0.000139,The California Department of Education receive...
7612,7613,7-29-20 Group School Board Letter.pdf,Comments Received After Field Review,33,0.000573,The California Department of Education receive...

In [101]:
duplicates.to_csv('duplicates.csv', index=False)

In [100]:
df['submissions'].sum()

74466

# Pdfs of Only Duplicate Comments

In [91]:
import os

copies_folder = os.path.join("/Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs")

valid_files_lower = set(f.strip().lower() for f in duplicates['file_name'].unique())

# recursively go through all subfolders
for root, dirs, files in os.walk(copies_folder):
    for file in files:
        file_path = os.path.join(root, file)
        # delete file if it's not in the dataframe
        if file.lower() not in valid_files_lower:
            os.remove(file_path)
            print("Deleted:", file_path)

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/.DS_Store
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-26-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Jesman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-26-20 Friedberg.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-5-20 Smith Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Metzger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-7-20 Shields.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/.DS_Store
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-7-20 Deurdulian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-21-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-12-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-2-20 Sadowsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-23-20 Chang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-2-20 Macgregor.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-2-20 Shufutinsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Parker Rod.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-14-20 Lee.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-8-20 Diwan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-19-20 Parker 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-4-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-19-20 Parker 3.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Shufutinsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Feinsmith.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-5-20 Smith.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Walsh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Cohen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Zhang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-7-20 Fong.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Benmoshe.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-26-20 Smith.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-9-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-5-20 Chiu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Sato.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-28-20 Presher.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-5-20 Marriott.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Jordan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-2-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Mound.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Myers and Shmueli 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-4-20 Chukwu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 TJK.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-22-20 Pinkston.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Samper.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-14-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-26-20 Parker 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Soelberg.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-9-20 Chin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 McNulty.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-28-20 Burke.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Taubman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/11-4-20 Yudof.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-13-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Klein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-23-20 Karapetian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-5-20 Maeshiro.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-1-20 Nash.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-23-20 Maria K.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-19-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-12-20 Parker 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-12-20 Haufrect.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-2-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-2-20 Boyd.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-14-20 George.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-30-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-22-20 Nash.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Parker 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/10-27-20 Fishkoff.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sarfeh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-17-20 Dolan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Nelson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Song.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Joudeh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-06-20 Allen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Khateeb.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ismail.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Harmachis.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Park.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Tsai.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 DeGange 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Pickus.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Chandler.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Johnston.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Finkelstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lewis 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Tani.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Halaby.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Weible.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Rovinsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Hershcopf.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Duhl.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Lerman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Cordero.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Azoury.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Douglas.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Epstein et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Post.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Kandawalla.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Bloom.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Najjar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Johnson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-23-20 Goldfinger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Christian.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Yadegar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Mulford.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/.DS_Store
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Williams.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Hollingsworth.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lazzouni.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Mushtaq.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Post .pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Fox.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Zelaya.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Martinez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ajluni.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ethnic and Cultural Affairs Commission.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parra.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Kaur and Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Poon.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Jarmakani.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Attachment 3.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Jones.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Feldman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ingenthron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Homsi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-20-20 Winograd.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Cho.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 APT.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Levin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Duron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Cheney.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Marchi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Alliance for Constructive Ethnic Studies.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Nina.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Koretz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Dibas.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Olvera.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Yeung.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Idoui.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Schwartz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Abajian et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Wan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Damsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sabreen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Tannous.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Yick.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Chang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Barasch.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Ehrlich.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kay.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Armen et al Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Block.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem .pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sussman et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kaufman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Lepawsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Altamimi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-2- Khalili.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Fishkin .pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Saville.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Brotsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ahmad.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Curry.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Romano.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Soroushian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Turman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-08-20 Smith.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Kahn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Blumberg.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Ophir.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sussman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Greenfield.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Clark.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Freeman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Chedekel .pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Gomez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Elchaer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Cavillones.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Tse.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Hsiao.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Villegas.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Blumenthal.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Rose.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-14-20 Nammar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/9-12-19 Muwwakkil.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Weinstock.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Schutt.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Chernyak.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Cappellanti-Adams.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Feilsticker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Baker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-23-20 Ladenheim.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Borenstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Prabhjot Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Gersten.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Lavic.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/DeLozier.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Sikh Coalition.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Lady C.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Pollock.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-18-20 Hussain Lubna.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Ryan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Sayre.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Chegwidden.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-18-20 Syed.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Polchow.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Elwood.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-28-20 Genera.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-26-20 Lieu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Rozencwaig.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Stone.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Skolnick.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-21-20 Najjar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/2-5-20 Moore.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/9-3-19 Atherton.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Astrof.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Mandair.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Shugarman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/1-6-20 Davidson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Goldman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/9-3-19 Council.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Imtair.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Martin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-20-20 Larsen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Paulino.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Aaronson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Shrayber.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-6-20 Mixter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Haller.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-16-20 Hendel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-30-20 Browning.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/2-18-20 Edminster.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Levitan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Rhoades.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Bendor.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-21-20 Bouskila.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-14-20 Saba.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/STEVENS.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Folger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-13-20 Dolsen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Peters.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Escobar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/2-6-20 Arellano.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Elliott.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/3-30-20 N Kaur.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Pardeep Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-17-20 Salome.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Manuel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Golner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-19-20 Islam.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/9-19-19 Jeung.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-8-20 Diller.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Rones.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-18-20 Soroya.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Persky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Schwartz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Pearlmutter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/11-5-19 Hirschhaut et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/1-8-20 Zilberstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Kiroun Saluja.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-21-20 Abajian et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Dulski.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Hendel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-6-20 Marty.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-25-20 JCRC.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-18-20 Hussain.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-30-20 Stacy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/3-27-20 P Kaur.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Sleeter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/.DS_Store
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Koren.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 S Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Wurtele.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Taylor.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-2-20 Save CA Ethnic Studies 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-3-20 Merkulova Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/11-9-19 Lara.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Draper.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/10-21-19 Abajian et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/3-24-20 Sahota.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Hakimian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Kean  Gold.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Mailhot.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Provance.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Duron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/12-6-19 Kenney.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Brunshteyn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Kim.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-3-20 Hong.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Lahav.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-30-20 Offerman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/3-30-20 V Sandhu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-26-20 Gallegos-Diaz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Dayan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-3-20 Campbell.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Moss.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Kieschnick.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-6-20 Mokatrin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Cuauhtin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/1-13-20 Fouda.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Kanwar Saluja.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-2-20 Koessel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-13-20 Armenian American Studies Collective.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Tabrizizadeh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Rozencwaig.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-14-20 Hollingsworth.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-15-20 Shaiq.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/8-26-19 Breslauer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-15-20 Kandawalla.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-15-20 Omar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Khalaf.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-31-20 Hamilton.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Walton.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Markevich.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Gonzales.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-24-20 Levy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-19-20 Khemici.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Roberts.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-27-20 Cabal.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Bennett.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-29-20 Institute for Curriculum Services.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Roder.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 Deslippe.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Pietruszka.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-13-20 Morrar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/5-26-20 Sokolower.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Hindawi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-31-20 Trepanier.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-27-20 Cava.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Bertet.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/10-14-19 Drapkin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/2-6-20 Tanner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-28-20 Rita A.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/10-16-19 Wood.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-13-20 Chheda.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 H Shergill.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Luo.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/6-18-20 Abukhazneh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/3-27-20 H Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Dahl.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/2-7-20 Ammari.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-30-20 Spangle.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/11-21-19 Garcia.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Hunt.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/4-1-20 H Singh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Gilad.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Moore.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/7-15-20 Brotsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/9-12-19 Bhujwala.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Kaur.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-24-20 Barrow.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Montano.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Mendelsohn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Miller.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Mabel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-7-20 McCauley.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Feldman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Bobrove.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Cavillones.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Hubis.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Donsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Louie.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Montalvo.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-23-20 Fried.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Khateeb.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Legion.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Riechel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Fa.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Maya.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Finsten.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Kava.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-7-20 Washington.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Jacobson Jo-Ann.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Smith Marion.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Wan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Bank.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Venasithamby.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Bodin Miriam 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Mizrahi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Levy Robert.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Fisher.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Bernal.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Issa.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Toomey.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-7-20 Woon.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Ferber.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-19-20 Woodcock.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Frangieh.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Gonzalez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-3-20 Landau.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Windham.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Thew.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Alznati.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-28-20 Sylvester.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Solouki.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Nalven.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Harari Emily.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Jordan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-14-20 Traish.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Zahzah.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Moreno.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Muna.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Lynn Attachment.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Masina.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Yelowitz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Davis Eric.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Levine.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Kheifets.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Jacobs.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Mandel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-14-20 Yeung.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Erickson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-5-20 Goraleski.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Tovo.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-16-20 Linder.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Alas.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-28-20 Sherman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Erikat.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Carter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 James.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Levin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Mogannam.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Kurtze.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-17-20 Shamolian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Erba.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Griffin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Chanukov.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Desta.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Carmel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Danzig.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-14-20 JIMENA.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Harris.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-31-20 Sweeney.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-3-20 Lipman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Fried.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-31-20 O'Leary.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Gur.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Bodin Douglas.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-24-20 Dorenz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Lips.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/08-12-20 Amin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Eskenazi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Joelson Michelle.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-12-20 Niku.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Sheff.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Shamban.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-3-20 Dorenz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Donsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Schapira.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Gould.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Jacobson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Leland.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Gabriel P.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Gereboff.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-6-20 Green.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-14-20 Kaur Prabhleen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Gershater.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Wager.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Shamis.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Wahba.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Laura Ng.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Chang et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-16-20 Singh 5.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Friedenthal Ron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Loeb.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-15-20 Gadisman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-14-20 Hirsekorn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Tuchfeld.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Majdal Center.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Hogue.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-11-20 Sacramento Area Peace Action.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Cadora.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Shur.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Kosinovsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-10-20 Jugo.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Comments Received After Field Review/Comments received after 7-31-20 posting/8-13-20 Zhu.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Oudiz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Feldman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Leiner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Ballard.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 MALLIN.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Simons.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Jakubovits.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Monteiro.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Eger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Bibayan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Vaysleb.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Foster.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Bernhard.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Moore.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Hobson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Bass.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Landsbaum.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Madrid.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Brinser.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Klerman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Armenian National Committee.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Lebowitz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Jurkovich.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Kujawsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Sahar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Littman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Hage.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Howell.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Drabkin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Zinn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Clark.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Bendetz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Harris.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Russell.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Stein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Isaacs.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Fishkin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Spivack.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Block.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Davis10.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Goldstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Locker .pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Amy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Elias4.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ionis.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Michael.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gonzalez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Moe.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 777.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Moore.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Sadeh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Sigman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Slavitt.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Liber.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Jacobson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Besone.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Everett.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Cantarutti.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Reiner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Weintraub.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 May.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Cohen docx.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Ames.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Clark.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Donahue.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Weiss.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Nourafshan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Maggs.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Fraser.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Gabelko.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Dworitz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Fliegelman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Fiss.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Garrett Amy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 St.Clair.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Schechter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Mendizaa.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ciner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Wieder.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Mire.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Marks.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Lovinsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Waghalter.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Miller.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Brandt.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Rappaport.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Halbur .pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Burke.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 DeMario docx.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Pierluissi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Yang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Moffa.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Zidel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Koff.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 cohn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Sanders.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Ben-David.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Frankl.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 RINGOLD.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Block.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Straus.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Hamlin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Ozdil.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Freeman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Karpel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Simpson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Sergant 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Zurnamer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Becker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Dao.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Weiss.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Herb.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Baron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Enzer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Goldzweig.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Leland.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Oliver.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Goldburg David.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Lee.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Naiman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Melamed.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Alderman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Bernstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Mitchell.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Shorr.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Hoffmaster.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Moghimi.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Hipp.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Elkayam.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Pritikin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Mohsin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 King Hannah.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Wilson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Pelan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Shaw.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Sanchez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Shooshani.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Kritzer 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Tokar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Luner.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Levy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Freier.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Elais.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Zudkewichdocx.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Kosinovsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Dryden.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Post.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Nahum.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Mejia-Gewe.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Saperstein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Haziza.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Shalon.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Schlessinger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Socol.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Leib Caren.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Kroop.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Rubin Marilyn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Kohanzadeh.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Portnoy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Lee.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 barlaz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Bowes.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gold.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Pavlow.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Aron.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Josephs.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Nudel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Schwartz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Sherman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Schusterman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Schuyler.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Ruben.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Feifer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Donnelly.pdf

Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Burns et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Banayan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Castroll.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-25-20 Kuchinsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-21-20 Sun.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Cain.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-4-21 Burke.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Horowitz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-21-20 Zhang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-6-21 Feltman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Schlacht.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Chang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Yuan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Lapidus.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Afary.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Moran.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Jakubowicz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Kaur and Singh Attachment 4.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Tracht.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Songey.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Becker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-17-20 Zhou.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Burns.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Bass.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Fenton.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-21-20 Frey.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Zarrow.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-18-20 Zhu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Peet.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Brown.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Nankin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Ehrlich.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Kohorn.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Schaffer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Leston.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-15-21 Moreland.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Krivacsy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Sarkin.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Nalven.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Feiman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Saavedra.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Shigemitsu.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-29-20 Fine.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-23-20 Fernandez.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Obsatz.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-18-20 Baker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Maguire.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Shakiban.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Palestine Solidarity Committee.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Angel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Rosenberg.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Dintzer.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-5-21 Hood.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Brott.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Merczak.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-23-20 Eisler.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Friedman Alex.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Abajian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Appel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Henningsen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Nadler.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Wycoff.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Better Ethnic Studies.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Felix D.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Koken.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Kaur and Singh Attachment 1.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-18-20 Fan.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-18-20 Xia.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Jefferson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Escobar.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Parker 3.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Pechenik.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 DiDonato.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Barembaum.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Wheeler.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Ohanian.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Yang.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-6-21 Hope.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Qussiny.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-15-21 Roman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Garson.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Healy 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-24-20 Frey.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Moreno.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-11-21 Parker.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Handel.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Villarreal.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Plapinger.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Kim.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Cevallos et al.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-18-20 Phillips.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Yuen.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-7-21 Fisher.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-22-20 Usher.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Ethnic Studies Organizing.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Termeie.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/12-14-20 Helman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Friedman.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Garshofsky.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Braum.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Kaufman Jeremy.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-19-21 Parker 2.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Stein.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-21-21 Schlosberg.pdf
Deleted: /Users/maryamzakiyya/Desktop/NLP URAP/ethnicStudiesNLPResearch/Text Files/Text Files/duplicate_handling/duplicate_pdfs/Third Field Review (Dec 2020 - Jan 2021)/1-20-21 Abad.pdf

In [92]:
pdf_count = 0

for root, dirs, files in os.walk(copies_folder):
    for file in files:
        if file.lower().endswith(".pdf"):
            pdf_count += 1

print(f"Total PDF files: {pdf_count}")

Total PDF files: 91

# Illegible Texts Inspection

In [97]:
print(df.iloc[6331]['text'])

August 22, 2020

By electronic delivery only

Members of the Instructional Quality Commission California Department of Education 1430 N Street Sacramento, CA 95814-5901 ethnicstudies@cde.ca.gov

RE: Revised Ethnic Studies Model Curriculum

Dear Members of the Instructional Quality Commission:

I am a parent of three children who have gone through the public education system in California. My youngest son is currently a high school senior and is in the process of applying for college. I am writing to comment on the revised Ethnic Studies Model Curriculum (ESMC) released on July 31. My family and I wholeheartedly endorse the teaching of Ethnic Studies and we support Assembly Bill 331. Adding Ethnic Studies to California's high school curriculum will, among other things, foster respect between students and an appreciation for our state and country's rich and diverse population.

I wish to express my support for the removal of overt antisemitism and extreme and gratuitous anti-Israel bias from the revised ESMC draft. Unfortunately as a Jewish family, each of my three sons has personally experienced antisemitism in the public school system. We chose the public school system so that our kids would learn and play and grow in a culturally diverse environment. I feel strongly that students' backgrounds and differences should be honored and respected. My middle son, now a senior at UCLA, had the opportunity to travel to Israel as part of a delegation of mostly non-Jewish campus leaders to better understand the Israeli-Palestinian conflict. He spent equal time with Palestinian leaders as he did with Jewish community leaders. My son is now minoring in Arabic and hopes to eventually work in diplomacy. Hopefully the final draft of the ESMC will include that spirit of cooperation and understanding, without negativity, so that our future generations will do a better job at embracing and honoring our diversity.

Best Regards, Rancy Feldman [address redacted] Palm Desert, CA [email redacted]

# Duplicates Breakdown

In [102]:
dupe_antisemitism = pd.read_csv('duplicates _updated.csv')
dupe_antisemitism

,Unnamed: 0,file_name,folder_name,submissions,weight,text,jew_antisemitism
0,30,11-12-20 Group Letter Critical Race Theory.pdf,"Comments Received After September 30, 2020",5,0.000040,The California Department of Education receive...,0
1,42,11-12-20 Group Letter Protect Butler.pdf,"Comments Received After September 30, 2020",3100,0.024743,The California Department of Education receive...,1
2,160,11-11-20 Group Letter Arab Americans 2.pdf,"Comments Received After September 30, 2020",4600,0.036716,The California Department of Education receive...,0
3,224,11-11-20 Group Letter Remove Political Agenda.pdf,"Comments Received After September 30, 2020",273,0.002179,The California Department of Education receive...,0
4,262,11-11-20 Group Letter Guiding Principles.pdf,"Comments Received After September 30, 2020",271,0.002163,The California Department of Education receive...,0
...,...,...,...,...,...,...,...
86,7057,7-8-20 Group Letter Arab American Studies.pdf,Comments Received After Field Review,10000,0.173633,The California Department of Education receive...,0
87,7181,7-24-20 Group Letter Protest Draft.pdf,Comments Received After Field Review,200,0.003473,The California Department of Education receive...,1
88,7456,1-29-20 Group Email Arab American Studies.pdf,Comments Received After Field Review,900,0.015627,The California Department of Education receive...,0
89,7478,7-8-20 Group Letter anti-BDS.pdf,Comments Received After Field Review,8,0.000139,The California Department of Education receive...,1
90,7613,7-29-20 Group School Board Letter.pdf,Comments Received After Field Review,33,0.000573,The California Department of Education receive...,0

In [104]:
dupe_antisemitism[dupe_antisemitism['jew_antisemitism'] == 1]['submissions'].sum()

37105

In [1]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('all_files.csv')
df

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [3]:
df['folder_name'].unique()

array(['Comments Received After September 30, 2020',
       'Third Field Review (Dec 2020 - Jan 2021)',
       'Second Field Review (Sept 2020)',
       'Comments Received After Field Review',
       'Comments received after Third Field Review (after 1-21-21)',
       'First Field Review (June - August 2019)'], dtype=object)

In [7]:
df[df['folder_name'].str.contains('First Field Review', case=False)]

,Unnamed: 0,file_name,folder_name,submissions,weight,text
1736,1736,8-7-19 Peters.pdf,First Field Review (June - August 2019),1,0.000018,"From: Lorin Peters Sent: Tuesday, August 6, 20..."
1737,1737,8-7-19 Pastcan.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...
1738,1738,8-13-19 Friedman.pdf,First Field Review (June - August 2019),1,0.000018,"From: Mona S Marley Sent: Tuesday, August 13, ..."
1739,1739,8-9-19 Kronick.pdf,First Field Review (June - August 2019),1,0.000018,"From: Mel Kronick Sent: Friday, August 9, 2019..."
1740,1740,8-8-19 Vosicher.pdf,First Field Review (June - August 2019),1,0.000018,"From: Sally Vosicher Sent: Thursday, August 8,..."
...,...,...,...,...,...,...
5866,5866,8-9-19 Gale.pdf,First Field Review (June - August 2019),1,0.000018,"258 A St, Ste.1, PMB 118\nAshland, OR 97520 ki..."
5867,5867,8-9-19 Hiatt.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template-2020 Ethnic Studies Mode...
5868,5868,8-13-19 Levi.pdf,First Field Review (June - August 2019),1,0.000018,﻿8/9/2019\nSuperintendent Tony Thurmond\nState...
5869,5869,8-9-19 Cohon.pdf,First Field Review (June - August 2019),1,0.000018,Regarding: California Ethnic Studies Model Cur...
5870,5870,8-14-19 Agoura Hills.pdf,First Field Review (June - August 2019),1,0.000018,﻿CITY OF AGOURA HILLS\n“Gateway to the Santa M...