In [1]:
import pandas as pd

/Users/maryamzakiyya/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
import os

# Path to the "samples" folder (assuming it's in the same directory as your notebook)
samples_path = "sampled_pdfs"

# Initialize counter
pdf_count = 0

# Walk through all subfolders and files inside "samples"
for root, dirs, files in os.walk(samples_path):
    for file in files:
        if file.lower().endswith(".pdf"):
            pdf_count += 1

print(f"Total number of PDFs in '{samples_path}' and its subfolders: {pdf_count}")

Total number of PDFs in 'sampled_pdfs' and its subfolders: 63

In [4]:
df = pd.read_csv("unique_sampled_all.csv")
df

,file_name,folder_name,count
0,8-15-19 Israeli American Council.pdf,First Field Review (June - August 2019),73
1,7-8-20 Group Letter Arab American Studies.pdf,Comments Received After Field Review,53
2,8-26-20 Group Letter Armenian American.pdf,Comments Received After Field Review,31
3,11-12-20 Group Letter Protect Butler.pdf,"Comments Received After September 30, 2020",13
4,9-2-20 Group Letter Jewish Americans.pdf,Second Field Review (Sept 2020),12
...,...,...,...
58,8-13-19 Levitan.pdf,First Field Review (June - August 2019),1
59,8-13-19 Miller Edward.pdf,First Field Review (June - August 2019),1
60,1-21-21 Hurd.pdf,Third Field Review (Dec 2020 - Jan 2021),1
61,8-15-19 Group Concern ESMC posted is dangerous...,First Field Review (June - August 2019),1
62,Roder.pdf,Comments Received After Field Review,1

In [5]:
all_files = pd.read_csv("all_files.csv")
all_files

,Unnamed: 0,file_name,folder_name,submissions,weight,text
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,..."
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem..."
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu..."
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18..."
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe..."
...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2..."
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2..."
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv..."
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ..."
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ..."

In [7]:
df['count'].sum()

300

In [8]:
df_remaining = all_files.merge(df, how='left', indicator=True)
df_remaining = df_remaining[df_remaining['_merge'] == 'left_only'].drop(columns='_merge')
df_remaining

,Unnamed: 0,file_name,folder_name,submissions,weight,text,count
0,0,11-13-20 Khan.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Hareem Khan Sent: Thursday, November 12,...",NaN
1,1,11-13-20 Solkovits.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: gs <gsolk@aol.com> Sent: Thursday, Novem...",NaN
2,2,11-13-20 Kaur and Singh.pdf,"Comments Received After September 30, 2020",1,0.000008,"November 13th, 2020\n\nDear Superintendent Thu...",NaN
3,3,11-19-20 Lamont.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sami Lamont Sent: Wednesday, November 18...",NaN
4,4,11-18-20 Jensen.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sine Hwang Jensen Sent: Tuesday, Novembe...",NaN
...,...,...,...,...,...,...,...
7712,7713,10-27-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Monday, October 26, 2...",NaN
7713,7714,10-30-20 Parker.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Friday, October 30, 2...",NaN
7714,7715,10-22-20 Nash.pdf,"Comments Received After September 30, 2020",1,0.000008,"Amin Nash, M.A. 10.21.2020\n\n1\n\nTo Executiv...",NaN
7715,7716,10-27-20 Parker 2.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Ruth Parker\nSent: Tuesday, October 27, ...",NaN
7716,7717,10-27-20 Fishkoff.pdf,"Comments Received After September 30, 2020",1,0.000008,"From: Sue Fishkoff\nSent: Monday, October 26, ...",NaN

In [9]:
df_new_sample = df_remaining.sample(n=63, random_state=42)
df_new_sample

,Unnamed: 0,file_name,folder_name,submissions,weight,text,count
7310,7311,7-27-20 Ditore.pdf,Comments Received After Field Review,1,0.000017,"From: Steve Ditore\nSent: Monday, July 27, 202...",NaN
4112,4112,8-6-19 Kendal.pdf,First Field Review (June - August 2019),1,0.000018,"From: Shawn Kendal Sent: Tuesday, August 6, 20...",NaN
5020,5020,8-9-19 Mandell.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...,NaN
836,836,1-20-21 McQuillen.pdf,Third Field Review (Dec 2020 - Jan 2021),1,0.000009,"From: Jim McQuillen Sent: Wednesday, January 2...",NaN
2181,2181,8-13-19 Reed.pdf,First Field Review (June - August 2019),1,0.000018,"From: Michael Reed Sent: Monday, August 12, 20...",NaN
...,...,...,...,...,...,...,...
6517,6518,9-30-20 Rosenheim.pdf,Second Field Review (Sept 2020),1,0.000011,"From: Becky Rosenheim Sent: Wednesday, Septemb...",NaN
7466,7467,7-27-20 Shapiro.pdf,Comments Received After Field Review,1,0.000017,"From: Larry Shapiro\nSent: Sunday, July 26, 20...",NaN
2537,2537,8-7-19 Schvimmer.pdf,First Field Review (June - August 2019),1,0.000018,Public Input Template�2020 Ethnic Studies Mode...,NaN
4572,4572,8-15-19 Karni.pdf,First Field Review (June - August 2019),1,0.000018,"From: Joe Karni Sent: Thursday, August 15, 201...",NaN
513,513,1-19-21 Sara H.pdf,Third Field Review (Dec 2020 - Jan 2021),1,0.000009,"From: Sara H Sent: Tuesday, January 19, 2021 1...",NaN

In [13]:
from pathlib import Path

# Path to your main folder
base_path = Path("copied folders")

# Create a set of valid relative paths from your DataFrame
allowed_paths = set(df.apply(lambda row: f"{row.folder_name}/{row.file_name}", axis=1))

# Find all PDFs recursively
all_pdfs = [p for p in base_path.rglob("*.pdf")]

# Identify PDFs not in your DataFrame
extra_pdfs = [p for p in all_pdfs if str(p.relative_to(base_path)) not in allowed_paths]

print(f"Found {len(extra_pdfs)} extra PDFs. Deleting...")

# Delete the extra PDFs
for pdf in extra_pdfs:
    try:
        pdf.unlink()
        print(f"Deleted: {pdf}")
    except Exception as e:
        print(f"Could not delete {pdf}: {e}")

print("Cleanup complete ✅")

Found 7618 extra PDFs. Deleting...
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Jesman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Friedberg.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Smith Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Metzger.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Shields.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Deurdulian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-21-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Sadowsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Macgregor.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Shufutinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker Rod.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 Lee.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-8-20 Diwan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker 3.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Shufutinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Feinsmith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Smith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Walsh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Cohen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Zhang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Fong.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Benmoshe.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Smith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-9-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Chiu.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Sato.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-28-20 Presher.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Marriott.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Jordan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Mound.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Myers and Shmueli 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Chukwu.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 TJK.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-22-20 Pinkston.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Samper.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Soelberg.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-9-20 Chin.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 McNulty.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-28-20 Burke.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Taubman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Yudof.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-13-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Klein.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Karapetian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Maeshiro.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Nash.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Maria K.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Haufrect.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-2-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-2-20 Boyd.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 George.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-22-20 Nash.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Fishkoff.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sarfeh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-17-20 Dolan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Nelson.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Song.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Joudeh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-06-20 Allen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Khateeb.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ismail.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Group Letter Support JIMENA.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Harmachis.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Park.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Tsai.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 DeGange 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Pickus.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Chandler.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Johnston.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Group Letter Arab Americans 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Finkelstein.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lewis 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Tani.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Halaby.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Group Letter Remove Political Agenda.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Weible.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Rovinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Hershcopf.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Duhl.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Lerman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Cordero.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Azoury.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Douglas.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Epstein et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Post.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Kandawalla.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Bloom.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Najjar.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Johnson.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-23-20 Goldfinger.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Christian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Yadegar.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Mulford.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Williams.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Hollingsworth.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lazzouni.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Mushtaq.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Post .pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Fox.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Zelaya.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Martinez.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ajluni.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ethnic and Cultural Affairs Commission.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parra.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Kaur and Singh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Poon.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Jarmakani.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Attachment 3.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Jones.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Feldman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ingenthron.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Homsi.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Group Letter Protect Butler.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-20-20 Winograd.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Cho.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 APT.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Levin.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Duron.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Cheney.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Marchi.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Alliance for Constructive Ethnic Studies.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Nina.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Koretz.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Dibas.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Olvera.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Yeung.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Idoui.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Schwartz.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Abajian et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Wan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Damsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sabreen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Tannous.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Yick.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Barasch.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Ehrlich.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kay.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Armen et al Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Block.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem .pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sussman et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kaufman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 1.pdf

Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Desiderio.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Glenn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Wald.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Limor.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Drake.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Sirlin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Cohen Jay.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Bialick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Marvin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Zaslow.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Wallach.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Kalev.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Golden.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Greenspan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Winick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Harris.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Edelson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Fishkin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Sanchez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 RUSSELL.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Wilson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Finkel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Frank.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Haroush.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Schwall.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Yoder.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Sciupac.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Joelson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ballen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Clark.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Kemerer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Saroeun.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Williams.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Messe.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Eskridge.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Blum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hyun.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Karp.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Burland.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gray.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Tolchin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Berenson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Hong.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Feldman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Newfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Creager.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Davis.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Magursky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Skolnik.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hayon.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Dula.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Nelson Katie.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Greenblum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Asch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Taylor Carmen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Larson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Harari.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Rogaway.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Luchfeld.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Alston.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Green.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Abouaf.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Yaghoubi.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Miller.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Singer Ezequiel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Brown.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Velazquez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Londner.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Sherman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Greenberg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Toprakjian.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Sorrell.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Bragin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Oisboid.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Citron.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Phelan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Epstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Klimer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Feist.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Bank.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Glass 3.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Rodgers.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ross.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Kopelevich.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Globus.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Shekel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Ginzburg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Donovan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Spector 3.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Bendahan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Breier.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Edelman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Woodward.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Atkinson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Theep.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Levin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Lightman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Flewelling.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Berkovich.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Bagheri.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Allen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19  Soss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Dreyer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Curtis.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Taubman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Howitt.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Melton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Dorin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Nassi.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Goodman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ironi.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Kelly.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Cain.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Taylor.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Reed.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Josef.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Emery.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Hopstone.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Stone.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Stein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Halpern.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Friedman, Ellen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Cohen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Garcia-Sims.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Oudiz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Feldman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Leiner.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Ballard.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 MALLIN.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Simons.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Jakubovits.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Monteiro.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Eger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Bibayan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Vaysleb.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Foster.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Bernhard.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Moore.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Hobson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Bass.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Landsbaum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Madrid.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Brinser.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Klerman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Armenian National Committee.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Lebowitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Jurkovich.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Kujawsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Sahar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Littman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Hage.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Howell.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Drabkin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Zinn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Clark.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Bendetz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Harris.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Russell.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Stein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Isaacs.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Fishkin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Spivack.pdf

Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Dratch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Fox.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Carmel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Wignot.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Samson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Rush.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Roth.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Stewart.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Shkuratov.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Reinstein Lorraine.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Bobrove.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Sadovsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Johnson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Lieber.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Lub.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Whippman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Wachowiak.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/6-17-19 Nguyen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Johnston.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Blumenfeld.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Jacob.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Sklarz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-18 Kaplan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Llewelyn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Bouhadana.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Osofsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Klein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Danzig Dan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Shezifi Galit.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Merriam.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hsu.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 sos.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Nilsen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Schmieder.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 London.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Elias.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Van Houten.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Braslawsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Levenson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Dines.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Codman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Gulko.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Leifer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Cheng.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Horn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Fernandez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Golbus.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Klor.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Goldstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Bisno.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Gomberg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Charmack.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Jacoby.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Oring.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Sleigh.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Group Concern with exlcuding Jews.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Pérez2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Krentz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Friedman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Orfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Kleinbaum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Levinson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Cohen Susan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Zalk.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Golbus.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Bierman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Gocal.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Forman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Elias.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Cohe.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Hamel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Rita.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Isaacs David.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Ranch-Buhr.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Diamond.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Fahrenthold.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Lumer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hayter.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Graham.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Masinovsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Kessler.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Levine Desiree.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Holzberg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Gilmore.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Levy Ginger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Koatz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Shamban.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 adivi 2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Corman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Johnson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Aharon.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Coss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Bulkin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Tolbert.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Egel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hirsch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Pilloff.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Hirschmann.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Shane.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Baldwin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Schmelzer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-16-19 Hofheimer 2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Wouk.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Andranigian.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Levine.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Lubliner.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Snaid.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Young.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Weiner .pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Levine Norman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Meiselman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Krieger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Ash.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Schick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Wright.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Guthart.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Levy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Rabin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Sered.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Art.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Bernick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Oberman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Mourad.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Lerch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Namvar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Jorgensen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Mayblum-Boaz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Yoo.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Schvimmer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Shane.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Katchalski 2docx.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Page.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ganjian.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Sverdlo.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Shapiro.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Kashnow.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Blake.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Skurnick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Mendeloff.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Apfelberg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Danzig Joy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Levine.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Schilder.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Goldbaum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Marie.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Feinstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Kibbar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Atwell.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Ehrlich.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Rivera.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Mullinax.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Lloyd.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Gomez docx.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Goodman-Gargagliano.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Gluck.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Markel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Rabinovitch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Gause.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Webster.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Enriquez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Burger Joanne.pdf

In [14]:
samples_path = "copied folders"

# Initialize counter
pdf_count = 0

# Walk through all subfolders and files inside "samples"
for root, dirs, files in os.walk(samples_path):
    for file in files:
        if file.lower().endswith(".pdf"):
            pdf_count += 1

print(f"Total number of PDFs in '{samples_path}' and its subfolders: {pdf_count}")

Total number of PDFs in 'copied folders' and its subfolders: 31

In [17]:
import pandas as pd
from pathlib import Path

# Load your DataFrame
df = df_new_sample
df['file_name'] = df['file_name'].astype(str)

# Create a set of valid (folder_name, file_name) pairs
valid_files = set(zip(df['folder_name'], df['file_name']))

# Base folder
base_path = Path("copied folders")

# Count how many PDFs match the DataFrame
count_valid = 0
for pdf_path in base_path.rglob("*.pdf"):
    leaf_folder = pdf_path.parent.name
    pdf_name = pdf_path.name
    if (leaf_folder, pdf_name) in valid_files:
        count_valid += 1

print(f"Number of PDFs that match the DataFrame: {count_valid}")

Number of PDFs that match the DataFrame: 50

In [18]:
import pandas as pd
from pathlib import Path

# Load your DataFrame
df = df_new_sample
df['file_name'] = df['file_name'].astype(str)

# Create a set of valid (folder_name, file_name) pairs
valid_files = set(zip(df['folder_name'], df['file_name']))

# Base folder
base_path = Path("copied folders")

# Iterate through all PDFs and delete the ones not in valid_files
for pdf_path in base_path.rglob("*.pdf"):
    leaf_folder = pdf_path.parent.name
    pdf_name = pdf_path.name
    if (leaf_folder, pdf_name) not in valid_files:
        pdf_path.unlink()  # deletes the file
        print(f"Deleted: {pdf_path}")

Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Jesman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Friedberg.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Smith Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Metzger.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Shields.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Deurdulian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-21-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Sadowsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Macgregor.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Shufutinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker Rod.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2 Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 Lee.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-8-20 Diwan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker 3.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Shufutinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Feinsmith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Smith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Walsh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Cohen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Zhang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-7-20 Fong.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Benmoshe.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Smith.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-9-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Chiu.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Sato.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-28-20 Presher.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Marriott.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Jordan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-2-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Mound.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Myers and Shmueli 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Chukwu.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 TJK.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-22-20 Pinkston.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Samper.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-26-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Soelberg.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-9-20 Chin.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 McNulty.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-28-20 Burke.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Taubman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/11-4-20 Yudof.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-13-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Klein.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Karapetian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-5-20 Maeshiro.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-1-20 Nash.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-23-20 Maria K.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-19-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-12-20 Haufrect.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Meyers and Shmueli 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-2-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-2-20 Boyd.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-14-20 George.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-30-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-22-20 Nash.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Parker 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/10-27-20 Fishkoff.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sarfeh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-17-20 Dolan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Nelson.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Song.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Joudeh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-06-20 Allen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Khateeb.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ismail.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Group Letter Support JIMENA.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Harmachis.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Park.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Tsai.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 DeGange 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Pickus.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Chandler.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Johnston.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Group Letter Arab Americans 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Finkelstein.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lewis 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Tani.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Halaby.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Group Letter Remove Political Agenda.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Weible.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Rovinsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Hershcopf.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Duhl.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Lerman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Cordero.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Azoury.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Douglas.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Epstein et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Coalition Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Post.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Kandawalla.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Bloom.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Najjar.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Johnson.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-23-20 Goldfinger.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Christian.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Yadegar.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Mulford.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Williams.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Hollingsworth.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Lazzouni.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Mushtaq.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Post .pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Fox.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Zelaya.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Martinez.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parker Ruth 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Ajluni.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Kava 1.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ethnic and Cultural Affairs Commission.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Parra.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Kaur and Singh.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Poon.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Jarmakani.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 TQREJ Attachment 3.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Jones.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Feldman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Ingenthron.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Homsi.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Group Letter Protect Butler.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-20-20 Winograd.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Cho.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 APT.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Levin.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Duron.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Cheney.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Marchi.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Alliance for Constructive Ethnic Studies.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Shoman Nina.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-19-20 Koretz.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Dibas.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Olvera.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Yeung.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 2.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-10-20 Idoui.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-11-20 Schwartz.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Abajian et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Wan.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Damsky.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sabreen.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Tannous.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-16-20 Yick.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Chang.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Barasch.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-18-20 Ehrlich.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 King.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kay.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Armen et al Attachment.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Block.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Salem .pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Sussman et al.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-12-20 Kaufman.pdf
Deleted: copied folders/Comments Received After September 30, 2020/Comments received after 11-6-20 posting/11-13-20 Webber Attachment 1.pdf

Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Nussbaum.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Bartos.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Scanzano.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Kelvie.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Jordan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Torres-Gil.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 White.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Cave.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Trapp.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Hoffman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Chang.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Davis2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Kalmanson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Haff.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Hanono.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Matheis.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Feinstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Jochim.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Moore.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Demant.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Roberts.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Vaughan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Foxgrover.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Herman2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Specter.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Carmi.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Taubman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Klein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Pessot.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Hirschel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Parker.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Richman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Awad-Rashmawi.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Axelrod.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Polushkin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Beard.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Revzin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 White.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Fox.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Woo.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Wacks.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Chavez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Wilson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Post.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Kidder.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Goldfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Martin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Frankel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Ramin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Lakin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Montague.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Couper.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Skop.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Deetz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Krypel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Carmel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Dishon.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Silverman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Levy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Group Concern for Jewish and Israeli-American students.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-24-19 ICS Review.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Elhams.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Kim.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Blair.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Long2.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Rappaport.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Grice.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Darom.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Reiss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Starr.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Fisk.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Shaw.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Muench.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Zohar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Lederer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Kennedy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 McHatton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 So Knit We All.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Simmons.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Kilbourn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Kendall.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Daugherty.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Israeli American Council.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Levin Abigail.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Neydavoud.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Lawson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Cook.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Abbott.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Sandler.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 D.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Fausett.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gubman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Coakley.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Huey.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Sklar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Baltinester.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Walton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Younger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Avraham.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Amitin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Kravitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Guerrero.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Foda.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Bendahan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Spiegel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19  Raufman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Zev.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Kadar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Ludwick.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Corney.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Tanz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Velasquez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Josephson .pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gotesdyner.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Soomekh.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Eizips.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Janger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Parks.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Sadikoff.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Apfelzweig.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Avrutin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Gila K.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Beck.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Baumwald.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Itzikowitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Geller.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Merkulova.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Jatzir.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Singer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Livingston.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Emrani.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Weiss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Moss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Scott.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 ROSEN.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Julia.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Topp.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Frank.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Conn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Stein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Gordonson .pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Fox docx.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Gentile.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Golchet.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Ross.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Ajluni.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Lamar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Sandel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Levy Italy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Twito.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Denton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Valfer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Sellers.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-2-19 Sleeter.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Clark.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Markovitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Feifel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Rosen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Long3.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Scott.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 becker.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Stone.pdf

Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Cohen Judith.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Armbruster.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Beltran.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Keegan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Ozello.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Winer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-31-19 Hockett.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Shpall.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Baitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Kranser.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Segal.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Miller Joe.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Handyside.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Stahl.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Baker.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Branch.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Tamara.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Deshotels.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Driver.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Benor.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Weitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Nelson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Nikravesh.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Zahriya.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Cosman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Gold.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Olesen.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Moss .pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Levine Marc.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Moreh.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19  Glass.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hyman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Golerkansky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Kobi M.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Group Supporting Ethnic Studies.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Armin Jamie.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Norman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Kohanteb.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Sidorovsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Lawson Alec.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Templeton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Katan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Cho.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Greenberg.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Cooper.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Baers.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Starr.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Fialkoff.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Schriger.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Claudia.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Ma.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Dustin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Lenz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Stowe.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Konze.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Levine.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Kaye.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Huang.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Salas.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Cunanan.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Mokeddem.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Smart.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Bowles.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Niku.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Vaysman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Levinsohn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Davidson.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Figueroa.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/7-30-19 Gula.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Elnatan K..pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Kennedy Julie.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Orvis.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Rubenstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Gendelman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Hales.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Fishman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Katz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Trilokekar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Fox.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Bauman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 rodriguez.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Gordon.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Leizerovich.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Gayle.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Edelstein.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Spaulding.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Emerich .pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Newfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Shaw.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Moss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Saba.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Diverse Coalition.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Seamans.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Currah.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Stern Candice.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Aviel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Crankshaw.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Jarvis.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Winkler.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Yablon.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Davida.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Goodman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Wynar.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Haruyama.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Spitzer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Queller.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Barnes.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Preciado.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Evelyn.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Sussman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Settelma.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Shapero.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Murov.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Frid.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Branca.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-2-19 Cruz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Hom.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Hunt.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Roche.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Wu.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Shaffer.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Morrison.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Krinsky.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Glaser.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Harris 1.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Buss.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Ostwald.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Sadikoff Sandra.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Choplin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Baird.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Enfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Arfin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-6-19 Benyowitz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-10-19 Probst.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Kirby.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Tinkler.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Buchbut.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Victor.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Brumfield.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-1-19 Thomas.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Angel.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Liberman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Pollock.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Flournoy.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Adams.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Fenimore.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-9-19 Sands.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-5-19 Venasithamby.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Norton.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Fleming.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-14-19 Artal.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Baik.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Shatz.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-8-19 Glaser.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19  Yaangh.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Gellman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-12-19 Kotin.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-7-19 Ossman.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-13-19 Weber.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-11-19 Eigner.pdf
Deleted: copied folders/First Field Review (June - August 2019)/First Field Review (June - August 2019)/8-15-19 Halliwell.pdf

In [19]:
samples_path = "copied folders"

# Initialize counter
pdf_count = 0

# Walk through all subfolders and files inside "samples"
for root, dirs, files in os.walk(samples_path):
    for file in files:
        if file.lower().endswith(".pdf"):
            pdf_count += 1

print(f"Total number of PDFs in '{samples_path}' and its subfolders: {pdf_count}")

Total number of PDFs in 'copied folders' and its subfolders: 50

In [20]:
from pathlib import Path
import pandas as pd

# Assuming your DataFrame is df_new_sample
df = df_new_sample

# Base folder
base_path = Path("copied folders")

# Get all folder names (most granular) in "copied folders" and its subfolders
all_folders_in_path = {p.name for p in base_path.rglob("*") if p.is_dir()}

# Get unique folder names from DataFrame
folders_in_df = set(df['folder_name'].unique())

# Folders in filesystem but not in df
folders_only_in_fs = all_folders_in_path - folders_in_df

# Folders in df but not in filesystem
folders_only_in_df = folders_in_df - all_folders_in_path

print("Folders only in filesystem (not in df):", folders_only_in_fs)
print("Folders only in df (not in filesystem):", folders_only_in_df)

Folders only in filesystem (not in df): {'Comments received after 11-6-20 posting', 'Comments received after 7-31-20 posting', '.ipynb_checkpoints'}
Folders only in df (not in filesystem): set()

In [23]:
df_new_sample[df_new_sample['folder_name'].str.contains('Comments received after 7-31-20 posting')]

Empty DataFrame
Columns: [Unnamed: 0, file_name, folder_name, submissions, weight, text, count]
Index: []

In [26]:
df_new_sample['folder_name'].unique()

array(['Comments Received After Field Review',
       'First Field Review (June - August 2019)',
       'Third Field Review (Dec 2020 - Jan 2021)',
       'Second Field Review (Sept 2020)',
       'Comments received after Third Field Review (after 1-21-21)',
       'Comments Received After September 30, 2020'], dtype=object)

In [28]:
from pathlib import Path
import pandas as pd

# Assume your DataFrame is df_new_sample
df = df_new_sample
df['file_name'] = df['file_name'].astype(str)
df['folder_name'] = df['folder_name'].astype(str)

# Create a set of valid (folder_name, file_name) from the DataFrame
df_files = set(zip(df['folder_name'], df['file_name']))

# Base folder
base_path = Path("copied folders")

# Create a set of existing PDFs in the folder (using leaf folder name)
existing_files = set()
for pdf_path in base_path.rglob("*.pdf"):
    leaf_folder = pdf_path.parent.name
    pdf_name = pdf_path.name
    existing_files.add((leaf_folder, pdf_name))

# Find files in df but not in copied folders
missing_files = df_files - existing_files

missing_files

{('Comments Received After Field Review', '8-10-20 Shapiro.pdf'),
 ('Comments Received After Field Review', '8-11-20 Heller.pdf'),
 ('Comments Received After Field Review', '8-11-20 Katriel.pdf'),
 ('Comments Received After Field Review', '8-11-20 Marvazy.pdf'),
 ('Comments Received After Field Review', '8-11-20 Volinsky.pdf'),
 ('Comments Received After Field Review', '8-12-20 Chanukov.pdf'),
 ('Comments Received After Field Review', '8-13-20 Laura Ng.pdf'),
 ('Comments Received After Field Review', '8-13-20 Samarov.pdf'),
 ('Comments Received After Field Review', '8-13-20 Traish Saidah.pdf'),
 ('Comments Received After Field Review', '8-13-20 Zhu.pdf'),
 ('Comments Received After September 30, 2020', '11-18-20 Sirkay.pdf'),
 ('Comments Received After September 30, 2020', '11-19-20 Tsai.pdf'),
 ('First Field Review (June - August 2019)', '8-5-19 Gitig.pdf')}